formatter: "markdown table"

version: ">= 0.16"

header-from: main.tf
footer-from: ""

recursive:
  enabled: false

sections:
  show:
    - requirements
    - inputs
    - outputs

content: |-
  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
