name: Bug Report
description: Create a report to help us improve
title: "[BUG]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out the information below to help us understand and reproduce the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the issue you encountered...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run terraform plan with...
        2. Set variables to...
        3. Execute terraform apply...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Terraform Configuration
      description: Please provide the relevant Terraform configuration
      render: hcl
      placeholder: |
        module "contrast_agent_injection" {
          # Your configuration here
        }
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/Error Messages
      description: Please include any relevant error messages or logs
      render: text
      placeholder: Paste error messages, stack traces, or relevant logs here...

  - type: input
    id: terraform-version
    attributes:
      label: Terraform Version
      description: What version of Terraform are you using?
      placeholder: e.g., 1.8.0
    validations:
      required: true

  - type: input
    id: module-version
    attributes:
      label: Module Version
      description: What version of this module are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: input
    id: aws-provider-version
    attributes:
      label: AWS Provider Version
      description: What version of the AWS provider are you using?
      placeholder: e.g., 5.0.0
    validations:
      required: true

  - type: dropdown
    id: agent-type
    attributes:
      label: Agent Type
      description: Which agent type are you using?
      options:
        - java
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, such as environment details, related issues, or potential solutions you've tried.
