name: Update Documentation

on:
  push:
    branches: [ main ]
    paths:
      - '*.tf'
      - 'variables.tf'
      - 'outputs.tf'
      - 'README.md'
      - 'examples/**'
  workflow_dispatch:

jobs:
  update-docs:
    name: Update Documentation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup terraform-docs
      uses: jaxxstorm/action-install-gh-release@v1.12.0
      with:
        repo: terraform-docs/terraform-docs
        tag: v0.17.0

    - name: Generate module documentation
      run: |
        terraform-docs markdown . --output-file README.md --output-mode inject

    - name: Generate example documentation
      run: |
        for example in examples/*/; do
          if [ -f "$example/README.md" ]; then
            echo "Updating documentation for $example"
            terraform-docs markdown "$example" --output-file "$example/README.md" --output-mode inject
          fi
        done

    - name: Check for changes
      id: verify-changed-files
      run: |
        if git diff --quiet; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi

    - name: Commit changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md examples/*/README.md
        git commit -m "docs: update terraform documentation" || exit 0
        git push
