name: Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

env:
  TF_VERSION: "1.12.2"

jobs:
  terraform-validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Validate Examples
      run: |
        for example in examples/*/; do
          echo "Validating $example"
          cd "$example"
          terraform init
          terraform validate
          cd - > /dev/null
        done

  terraform-test:
    name: Terraform Test
    runs-on: ubuntu-latest
    needs: terraform-validate
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: terraform init

    - name: Run Terraform Tests
      run: terraform test -verbose

    - name: Generate Test Report
      if: always()
      run: terraform test -junit-xml=test-results.xml
      continue-on-error: true

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results.xml

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: terraform-validate
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: terraform init

    - name: Run tfsec
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        working_directory: .
        format: sarif
        soft_fail: true

    - name: Upload SARIF file
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: tfsec.sarif

  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: latest

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint --format=compact

  docs-check:
    name: Documentation Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup terraform-docs
      uses: jaxxstorm/action-install-gh-release@v1.12.0
      with:
        repo: terraform-docs/terraform-docs
        tag: v0.20.0

    - name: Check documentation is up to date
      run: |
        terraform-docs markdown . > README_GENERATED.md
        if ! diff -q README.md README_GENERATED.md > /dev/null; then
          echo "Documentation is out of date. Please run 'terraform-docs markdown . > README.md'"
          echo "Differences:"
          diff README.md README_GENERATED.md
          exit 1
        fi
        echo "Documentation is up to date"
