name: Update Dependencies

on:
  schedule:
    # Run every Monday at 09:00 UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-terraform-providers:
    name: Update Terraform Providers
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.12.2"

    - name: Update Terraform Lock File
      run: |
        terraform init -upgrade
        
        # Check if there are any changes
        if git diff --quiet .terraform.lock.hcl; then
          echo "No updates available"
          echo "updates_available=false" >> $GITHUB_OUTPUT
        else
          echo "Updates available"
          echo "updates_available=true" >> $GITHUB_OUTPUT
        fi
      id: update_check

    - name: Run Tests with Updated Dependencies
      if: steps.update_check.outputs.updates_available == 'true'
      run: |
        terraform validate
        terraform test

    - name: Create Pull Request
      if: steps.update_check.outputs.updates_available == 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update terraform provider dependencies"
        title: "chore: update terraform provider dependencies"
        body: |
          This PR updates the Terraform provider dependencies to their latest versions.
          
          Changes:
          - Updated `.terraform.lock.hcl` with latest provider versions
          - All tests pass with the updated dependencies
          
          Auto-generated by the dependency update workflow.
        branch: update-terraform-dependencies
        delete-branch: true
